// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"
	dtos "vwap/pkg/dtos"

	mock "github.com/stretchr/testify/mock"
)

// VWAPCalculator is an autogenerated mock type for the VWAPCalculator type
type VWAPCalculator struct {
	mock.Mock
}

// CalcAvg provides a mock function with given fields: ctx, responseChan
func (_m *VWAPCalculator) CalcAvg(ctx context.Context, responseChan <-chan *dtos.Response) (<-chan *dtos.ProductAvgs, error) {
	ret := _m.Called(ctx, responseChan)

	var r0 <-chan *dtos.ProductAvgs
	if rf, ok := ret.Get(0).(func(context.Context, <-chan *dtos.Response) <-chan *dtos.ProductAvgs); ok {
		r0 = rf(ctx, responseChan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *dtos.ProductAvgs)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, <-chan *dtos.Response) error); ok {
		r1 = rf(ctx, responseChan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Close provides a mock function with given fields:
func (_m *VWAPCalculator) Close() {
	_m.Called()
}
