// Code generated by mockery v2.7.4. DO NOT EDIT.

package mocks

import (
	context "context"
	dtos "vwap/pkg/dtos"

	mock "github.com/stretchr/testify/mock"
)

// Websocket is an autogenerated mock type for the Websocket type
type Websocket struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Websocket) Close() {
	_m.Called()
}

// Connect provides a mock function with given fields: url
func (_m *Websocket) Connect(url string) error {
	ret := _m.Called(url)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, request
func (_m *Websocket) Subscribe(ctx context.Context, request *dtos.Subscription) (<-chan *dtos.Response, error) {
	ret := _m.Called(ctx, request)

	var r0 <-chan *dtos.Response
	if rf, ok := ret.Get(0).(func(context.Context, *dtos.Subscription) <-chan *dtos.Response); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *dtos.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dtos.Subscription) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
